export const DRAWING_ERRORS = {
  // 게임 상태
  GAME_STATE_NOT_FOUND: 'GAME_STATE_NOT_FOUND',

  // 페이즈 검증
  NOT_IN_DRAWING_PHASE: 'NOT_IN_DRAWING_PHASE',
  DRAWING_CONTEXT_MISSING: 'DRAWING_CONTEXT_MISSING',

  // 유저 검증
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',

  // 데이터 누락
  MATCH_ID_MISSING: 'MATCH_ID_MISSING',
  ROOM_MEMBER_MAP_MISSING: 'ROOM_MEMBER_MAP_MISSING',
  ROOM_MEMBER_ID_MISSING: 'ROOM_MEMBER_ID_MISSING',

  // 데이터 불일치
  ROOM_MEMBER_ID_DUPLICATED: 'ROOM_MEMBER_ID_DUPLICATED',
  ROOM_MEMBER_MAP_INVALID: 'ROOM_MEMBER_MAP_INVALID',
  DRAW_DATA_INVALID: 'DRAW_DATA_INVALID',
} as const;
