export const GAME_ERRORS = {
  PHASE_MUST_BE_LOADING: 'GAME_PHASE_MUST_BE_LOADING',
  PHASE_MUST_BE_THEME_SELECTING: 'GAME_PHASE_MUST_BE_THEME_SELECTING',
  CONTEXT_INVALID: 'GAME_CONTEXT_INVALID',
  PERMISSION_DENIED_SELECTOR: 'GAME_PERMISSION_DENIED_SELECTOR',
  THEME_INVALID: 'GAME_THEME_INVALID',
  THEME_NOT_SET: 'GAME_THEME_NOT_SET',
  GAME_UNAUTHORIZED: 'GAME_UNAUTHORIZED',
  GAME_INVALID_ROOM_ID: 'GAME_INVALID_ROOM_ID',
  GAME_ACCESS_DENIED: 'GAME_ACCESS_DENIED',
  GAME_CONTEXT_INVALID: 'GAME_CONTEXT_INVALID',
  INVALID_PHASE: 'INVALID_PHASE',
} as const;

export const GAME_EVENTS = {
  SYSTEM_NOTIFICATION: 'system:notification',
  GAME_JOINED: 'game:joined',
  ROOM_UPDATE_GAME_STATE: 'room:updateGameState',
  GAME_THEME_CONFIRMED: 'game:themeConfirmed',
  LOADING_STARTED: 'game.loading.started',
  ROOM_READY_TOGGLE: 'room:readyToggle',
  ROOM_UPDATE_PLAYER: 'room:updatePlayer',
  ROOM_UPDATE_READY_SUMMARY: 'room:updateReadySummary',
} as const;

export const GAME_DEFAULTS = {
  TOTAL_ROUNDS: 3,
  RECENT_THEMES_LIMIT: 3,
} as const;

export const GAME_TIMINGS = {
  THEME_SELECTING_DURATION_MS: 32000,
  DRAWING_DURATION_MS: 92000,
  EVALUATING_DURATION_MS: 60000,
  ROUND_SUMMARY_DURATION_MS: 32000,
  FINISHED_HOLD_MS: 8000,
} as const;
